replicaCount: 1

serviceAccount:
  create: true
  name: cluster-reader

image:
  repository: francescogalanti/flask-app-example  
  tag: latest       
  pullPolicy: IfNotPresent

namespace: formazione-sou

service:
  name: flask-app-service
  type: NodePort
  port: 8000
  targetPort: 8000
  nodePort: 30000

ingress:
  enabled: true                   
  hosts: 
    - "formazionesou.local"              
  annotations:
    kubernetes.io/ingress.class: nginx
  tls:
    - secretName: flask-app-tls     
      hosts:
        - formazionesou.local 

resources:
  limits:                             
    cpu: "500m"                        
    memory: "256Mi"                    
  requests:                            
    cpu: "250m"                
    memory: "128Mi" 

livenessProbe:
  httpGet:
    path: /
    port: 8000
  initialDelaySeconds: 5
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /
    port: 8000
  initialDelaySeconds: 5
  periodSeconds: 10
