# -*- mode: ruby -*-
# vi:set ft=ruby :

Vagrant.configure("2") do |config|

 config.vm.define "node1" do |node1|
  node1.vm.box = "bento/ubuntu-20.04"
  node1.vm.network "private_network", ip: "192.168.10.10"
  node1.vm.hostname = "node1"
  node1.vm.provider "virtualbox" do |vb|
    vb.memory = "512"
 end
  node1.vm.provision :shell, path: "pingpong.sh"
end

 config.vm.define "node2" do |node2|
  node2.vm.box = "bento/ubuntu-20.04"
  node2.vm.network "private_network", ip: "192.168.10.20"
  node2.vm.hostname = "node2"
  node2.vm.provider "virtualbox" do |vb|
    vb.memory = "512"
 end
  node2.vm.provision :shell, path:"pingpongnode2.sh"
 end
end
