---
- name: Install Apache and OpenSSL
  apt:
    name:
      - apache2
      - openssl
    state: present
    update_cache: true

- name: Enable necessary Apache modules
  shell: |
    a2enmod ssl
    a2enmod headers
    systemctl restart apache2

- name: Copy "Hello World" index.html
  copy:
    src: index.html
    dest: /var/www/html/index.html
    owner: www-data
    group: www-data
    mode: '0644'

- name: Create SSL directory
  file:
    path: /etc/apache2/ssl
    state: directory
    mode: '0700'

- name: Generate CA key and certificate
  command: >
    openssl req -x509 -new -nodes -keyout /etc/apache2/ssl/server.key -out /etc/apache2/ssl/server.crt
    -days 365 -subj "/CN=MySelfSignedCA"

- name: Generate a private key for server
  openssl_privatekey:
    path: /etc/apache2/ssl/server.key
    cipher: auto
    size: 2048

- name: Generate a CSR for server
  openssl_csr:
    path: /etc/apache2/ssl/server.csr
    privatekey_path: /etc/apache2/ssl/server.key
    common_name: "apache.local"
    country_name: "IT"
    organization_name: "Sourcesense"
    state_or_province_name: "Lazio"

- name: Generate a Self Signed OpenSSL certificate
  openssl_certificate:
    path: /etc/apache2/ssl/server.crt
    privatekey_path: /etc/apache2/ssl/server.key
    csr_path: /etc/apache2/ssl/server.csr
    provider: selfsigned

- name: Deploy Apache SSL configuration
  template:
    src: default-ssl.conf.j2
    dest: /etc/apache2/sites-available/default-ssl.conf

- name: Enable SSL site
  shell: |
    a2ensite default-ssl
    systemctl reload apache2

