Vagrant.configure("2") do |config|

 config.vm.define "node" do |node|
  node.vm.box = "ubuntu/jammy64"
  node.vm.network "private_network", ip: "192.168.10.100"
  node.vm.hostname = "soufe1"
  node.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end
 end
end

